### ISSUE TITLE
we can only buy the JetRacer component one by one?

### ISSUE THREAD

**Issue by Dep74** [NVIDIA-AI-IOT/jetracer#23]
Is there any link we can buy all the items in one package?

**Comment by jaybdub** [comment]
Hi Dep74,

Thanks for reaching out!  To my knowledge there currently are not any readily available third party JetRacer kits like there are for [JetBot](https://www.nvidia.com/en-us/autonomous-machines/embedded-systems/jetbot-ai-robot-kit/).

That said, please let me know if you have any questions or confusion on the bill of materials and I'm happy to help.  The feedback is very helpful for us and other users.

JetRacer or otherwise, I look forward to seeing what project you come up with :)

Best,
John
